### ISSUE TITLE
Unexpted error occured

### ISSUE THREAD

**Issue by praveenkumar** [strzibny/vagrant-routes#1]
I tried it for both Linux and Mac I got below output. For Linux it got added to /etc/hosts but for Mac their was **no entry** for this. I don't have windows machine handy so can't provide any input there but will try soon.

```
$ vagrant route
Updating hosts file with new hostnames:
nodejs-example-test.router.default.svc.cluster.local
Unexpected error occured.
```

**Comment by strzibny** [comment]
I need to include the real error in 'else' cause so we see what's wrong.

**Comment by strzibny** [comment]
I improved the error handling, can you try again and tell me what does it return?

Perhaps it has the following error?

```
The connection to the server 10.1.2.2:8443 was refused - did you specify the right host or port?
```

**Comment by strzibny** [comment]
This should be fixed now.
