### ISSUE TITLE
Use --config option to automatically become cluster admin

### ISSUE THREAD

**Issue by strzibny** [strzibny/vagrant-routes#2]
Given that OpenShift VM comes with a cluster configuration file, we can just use `--config=/var/lib/origin/openshift.local.config/master/admin.kubeconfig` with `oc get routes`.

**Comment by hferentschik** [comment]
that would still be a once off thing right? How would you make sure that new entries to /etc/hosts are made when a new application gets created?

**Comment by strzibny** [comment]
@hferentschik you can't, this is not a daemon like landrush, this is semi-automatic. It has its disadvantages (like this one) and advantages (zero-setup, nothing running, platform independent).

**Comment by strzibny** [comment]
This is now done in 0.0.6. Next step would be to make it configurable.

**Comment by hferentschik** [comment]
>  you can't, this is not a daemon like landrush

Could not not make it a daemon and use 'oc watch' to monitor the creation of new routes?

On a different note, is it possible to cache the credentials needed to modify the hosts file so that you would not have to provide them all the time? Does Vagrant not do this as well?

Last but not least, does _vagrant-routes_ mean, the idea of getting Landrush to work on Windows is abandoned?

**Comment by strzibny** [comment]
> Could not not make it a daemon and use 'oc watch' to monitor the creation of new routes?

Yes, we could.

> On a different note, is it possible to cache the credentials needed to modify the hosts file so that you would not have to provide them all the time? Does Vagrant not do this as well?

I believe this is a system thing.

Look here: https://github.com/smdahlen/vagrant-hostmanager#passwordless-sudo

> Last but not least, does vagrant-routes mean, the idea of getting Landrush to work on Windows is abandoned?

No. But I would rather provide users something until we have it working. This could be a temporal solution for libvirt/Windows users. And great alternative to landrush if you just need something simple.
